export const types = {
  CHANGE_PATH: "CHANGE_PATH",
  FETCH_CURRENT_AUDIO_REQUEST: "FETCH_CURRENT_AUDIO_REQUEST",
  FETCH_CURRENT_AUDIO_SUCCESS: "FETCH_CURRENT_AUDIO_SUCCESS",
  FETCH_CURRENT_AUDIO_ERROR: "FETCH_CURRENT_AUDIO_ERROR",
  FETCH_AUDIO_LIST_REQUEST: "FETCH_AUDIO_LIST_REQUEST",
  FETCH_AUDIO_LIST_SUCCESS: "FETCH_AUDIO_LIST_SUCCESS",
  FETCH_AUDIO_LIST_ERROR: "FETCH_AUDIO_LIST_ERROR",
  FETCH_DEVICE_LIST_REQUEST: "FETCH_DEVICE_LIST_REQUEST",
  FETCH_DEVICE_LIST_SUCCESS: "FETCH_DEVICE_LIST_SUCCESS",
  FETCH_DEVICE_LIST_ERROR: "FETCH_DEVICE_LIST_ERROR",
  SET_CURRENT_DEVICE: "SET_CURRENT_DEVICE",
};
